apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu

        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eslint
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to ESLint
      type: string
      default: "src/ tests/ --ext *.js"
    - name: path
      description: Directory (relative to workspace) that contains package.json
      type: string
      default: "."
  steps:
    - name: lint
      image: node:20-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e

        echo "Node: $(node -v)"
        echo "NPM:  $(npm -v)"

        cd "$(workspaces.source.path)/$(params.path)"

        if [ ! -f package.json ]; then
          echo "ERROR: package.json not found in: $(pwd)"
          echo "TIP: If your package.json is in a subfolder (e.g. service/), set param path=service in the Pipeline task."
          exit 1
        fi

        echo "Installing dependencies..."
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

        echo "Running ESLint..."
        npm run lint -- $(params.args)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jest-test
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to jest
      type: string
      default: "-v"
    - name: path
      description: Directory (relative to workspace) that contains package.json
      type: string
      default: "."
  steps:
    - name: jest
      image: node:20-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e

        echo "Node: $(node -v)"
        echo "NPM:  $(npm -v)"

        cd "$(workspaces.source.path)/$(params.path)"

        if [ ! -f package.json ]; then
          echo "ERROR: package.json not found in: $(pwd)"
          echo "TIP: If your package.json is in a subfolder (e.g. service/), set param path=service in the Pipeline task."
          exit 1
        fi

        echo "Installing dependencies..."
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

        echo "Running Jest..."
        npm test -- $(params.args)
