apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu

        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eslint
spec:
  workspaces:
    - name: source

  params:
    - name: path
      description: Directory that contains package.json for eslint
      type: string
      default: "service"
    - name: args
      description: Extra args passed to npm run lint (optional)
      type: string
      default: ""

  steps:
    - name: lint
      image: node:20-alpine
      workingDir: $(workspaces.source.path)/$(params.path)
      script: |
        #!/bin/sh
        set -eu

        echo "Working dir: $(pwd)"
        echo "Node: $(node -v)"
        echo "NPM:  $(npm -v)"

        if [ ! -f package.json ]; then
          echo "ERROR: package.json not found in $(pwd)"
          echo "TIP: set param 'path' to the folder that contains package.json"
          exit 1
        fi

        echo "Installing dependencies..."
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

        echo "Running ESLint..."
        if [ -n "$(params.args)" ]; then
          npm run lint -- $(params.args)
        else
          npm run lint
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jest-test
spec:
  workspaces:
    - name: source

  params:
    - name: path
      description: Directory that contains package.json for jest
      type: string
      default: "service"
    - name: args
      description: Extra args passed to npm test (optional)
      type: string
      default: "-v"

  steps:
    - name: test
      image: node:20-alpine
      workingDir: $(workspaces.source.path)/$(params.path)
      script: |
        #!/bin/sh
        set -eu

        echo "Working dir: $(pwd)"
        echo "Node: $(node -v)"
        echo "NPM:  $(npm -v)"

        if [ ! -f package.json ]; then
          echo "ERROR: package.json not found in $(pwd)"
          echo "TIP: set param 'path' to the folder that contains package.json"
          exit 1
        fi

        echo "Installing dependencies..."
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

        echo "Running Jest..."
        if [ -n "$(params.args)" ]; then
          npm test -- $(params.args)
        else
          npm test
        fi
