apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: Clean up workspace contents.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu

        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  description: Lint a Python project using flake8.
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to flake8
      type: string
      default: "."
  steps:
    - name: lint
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e

        python -m pip install --upgrade pip wheel
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

        pip install flake8
        echo "Running flake8..."
        flake8 $(params.args)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  description: Run Python unit tests using nose.
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to nosetests
      type: string
      default: "-v"
  steps:
    - name: test
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e

        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        pip install nose
        echo "Running nosetests..."
        nosetests $(params.args)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jest-test
spec:
  description: (Python version) Keep task name as 'jest-test' for the pipeline, but run Python tests.
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to tests
      type: string
      default: "-v"
  steps:
    - name: test
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e

        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt

        # Prefer nose if present in project, otherwise install
        pip install nose

        echo "Running tests (task name: jest-test)..."
        nosetests $(params.args)
