---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: main
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git:2.45.2
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -eu
        rm -rf ./* ./.??* || true
        git clone --depth 1 --branch "$(params.revision)" "$(params.url)" .
        git rev-parse HEAD

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      type: string
      description: Full image reference to push to
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable:v1.35.0
      workingDir: $(workspaces.source.path)
      securityContext:
        privileged: true
      script: |
        #!/bin/bash
        set -e
        echo "Building image: $(params.IMAGE)"
        buildah bud -t "$(params.IMAGE)" .
        buildah push "$(params.IMAGE)"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
spec:
  params:
    - name: app-name
      type: string
    - name: build-image
      type: string
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:4.16
      script: |
        #!/bin/bash
        set -e
        oc create deployment "$(params.app-name)" \
          --image="$(params.build-image)" \
          --dry-run=client -o yaml | oc apply -f -
