---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu

        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        # Delete any existing contents of the directory if it exists.
        #
        # We don't just "rm -rf ${WORKSPACE_SOURCE_PATH}" because ${WORKSPACE_SOURCE_PATH} might be "/"
        # or the root of a mounted volume.
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          # Delete non-hidden files and directories
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source

  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"

  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e

        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eslint
spec:
  description: Run eslint on a Node.js project.
  workspaces:
    - name: source
  params:
    - name: node-image
      type: string
      default: node:20-alpine
    - name: path
      type: string
      default: .
    - name: args
      type: array
      default:
        - .
  steps:
    - name: install-and-run
      image: $(params.node-image)
      workingDir: $(workspaces.source.path)/$(params.path)
      script: |
        #!/bin/sh
        set -eu
        node -v
        npm -v

        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

        # Ensure eslint exists
        if ! npx --yes eslint -v >/dev/null 2>&1; then
          npm install --no-save eslint
        fi

        npx eslint $(params.args[*])

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jest-test
spec:
  description: Run Jest tests for a Node.js project.
  workspaces:
    - name: source
  params:
    - name: node-image
      type: string
      default: node:20-alpine
    - name: path
      type: string
      default: .
    - name: args
      type: array
      default: []
  steps:
    - name: install-and-test
      image: $(params.node-image)
      workingDir: $(workspaces.source.path)/$(params.path)
      script: |
        #!/bin/sh
        set -eu
        node -v
        npm -v

        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

        if [ "${#params.args[*]}" -eq 0 ]; then
          npx jest
        else
          npx jest $(params.args[*])
        fi
